# Generated by Django 4.0.6 on 2022-08-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dirección', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_de_Dinero', models.FloatField(default=0)),
                ('Generación_de_Intereses', models.BooleanField()),
                ('Nro_Cuenta', models.BigIntegerField()),
                ('Orientación_de_Cuenta', models.CharField(choices=[('Corriente Personal', 'Corriente Personal'), ('Corriente Colectiva', 'Corriente Colectiva'), ('Corriente Coorporativa', 'Corriente Coorporativa'), ('Corriente Entidad Pública', 'Corriente Entidad Pública')], default='corriente personal', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.PositiveBigIntegerField()),
                ('Tipo_de_Sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default='Hombre', max_length=20)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contraseña', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Operaciones_Bancarias.persona')),
                ('Correo', models.EmailField(max_length=100)),
                ('Nro_Telefono', models.PositiveBigIntegerField()),
                ('Tipo_de_Cliente', models.CharField(choices=[('Benefactor', 'Benefactor'), ('Beneficiario', 'Beneficiario')], default='Beneficiario', max_length=20)),
            ],
            bases=('Operaciones_Bancarias.persona',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Operaciones_Bancarias.persona')),
                ('Cargo', models.CharField(max_length=100)),
                ('Tipo_de_Contrato', models.CharField(choices=[('Contrato por obra o labor', 'Contrato por obra o labor'), ('Contrato de trabajo a término fijo', 'Contrato de trabajo a término fijo'), ('Contrato de trabajo a término indefinido', 'Contrato de trabajo a término indefinido'), ('Contrato de aprendizaje', 'Contrato de aprendizaje'), ('Contrato temporal, ocasional o accidental', 'Contrato temporal, ocasional o accidental')], default='Contrato por obra o labor', max_length=50)),
            ],
            bases=('Operaciones_Bancarias.persona',),
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Problema', models.TextField()),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctn_list', to='Operaciones_Bancarias.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Divisa', models.CharField(choices=[('Dolar', 'Dolar'), ('Euro', 'Euro'), ('Yen Japones', 'Yen Japones'), ('Libra Esterlina', 'Libra Esterlina'), ('Franco Suizo', 'Franco Suizo')], default='Dolar', max_length=20)),
                ('Operacion_Bancaria', models.CharField(choices=[('Retiro', 'Retiro'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia')], default='Transferencia', max_length=20)),
                ('Monto', models.FloatField(max_length=7)),
                ('Cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones_Bancarias.cuenta')),
                ('Registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones_Bancarias.registro')),
                ('Cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones_Bancarias.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='Cliente_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_list', to='Operaciones_Bancarias.cliente'),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slct_list', to='Operaciones_Bancarias.solicitud')),
                ('Cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones_Bancarias.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.FloatField()),
                ('Plazo', models.IntegerField(help_text='meses')),
                ('Tipo_de_Prestamo', models.CharField(choices=[('Crédito productivo', 'Crédito productivo'), ('Crédito Comercial Ordinario', 'Crédito Comercial Ordinario'), ('Crédito Comercial Prioritario', 'Crédito Comercial Prioritario'), ('Crédito de Consumo Ordinario', 'Crédito de Consumo Ordinario'), ('Crédito Educativo', 'Crédito Educativo')], default='Crédito Educativo', max_length=40)),
                ('Divisa', models.CharField(choices=[('Dolar', 'Dolar'), ('Euro', 'Euro'), ('Yen Japones', 'Yen Japones'), ('Libra Esterlina', 'Libra Esterlina'), ('Franco Suizo', 'Franco Suizo')], default='Dolar', max_length=20)),
                ('ClienteList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_a_list', to='Operaciones_Bancarias.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Cliente_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_list', to='Operaciones_Bancarias.cliente'),
        ),
    ]
