# Generated by Django 4.0.6 on 2022-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='Nro_Cuenta',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Tipo_de_Sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default='Hombre', max_length=20),
        ),
    ]
