# Generated by Django 4.0.6 on 2022-08-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Cliente',
            field=models.ManyToManyField(blank=True, to='Operaciones_Bancarias.cliente'),
        ),
    ]
