# Generated by Django 4.0.6 on 2022-08-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0002_cuenta_remove_cliente_nro_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='Cliente_List',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cl_list', to='Operaciones_Bancarias.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='Cliente_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_list', to='Operaciones_Bancarias.cliente'),
        ),
    ]
