# Generated by Django 4.0.6 on 2022-08-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0002_alter_cuenta_nro_cuenta_alter_persona_tipo_de_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Tipo_de_Contrato',
            field=models.CharField(choices=[('Contrato por obra o labor', 'Contrato por obra o labor'), ('Contrato de trabajo a término fijo', 'Contrato de trabajo a término fijo'), ('Contrato de trabajo a término indefinido', 'Contrato de trabajo a término indefinido'), ('Contrato de aprendizaje', 'Contrato de aprendizaje'), ('Contrato temporal, ocasional o accidental', 'Contrato temporal, ocasional o accidental')], default='Contrato por obra o labor', max_length=50),
        ),
    ]
