# Generated by Django 4.0.6 on 2022-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0003_alter_empleado_tipo_de_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='Divisa',
            field=models.CharField(choices=[('Dolar', 'Dolar'), ('Euro', 'Euro'), ('Yen Japones', 'Yen Japones'), ('Libra Esterlina', 'Libra Esterlina'), ('Franco Suizo', 'Franco Suizo')], default='Dolar', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Monto',
            field=models.FloatField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Operacion_Bancaria',
            field=models.CharField(choices=[('Retiro', 'Retiro'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia')], default='Transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Tipo_de_Cliente',
            field=models.CharField(choices=[('Benefactor', 'Benefactor'), ('Beneficiario', 'Beneficiario')], default='Beneficiario', max_length=20),
        ),
    ]
