# Generated by Django 4.0.6 on 2022-08-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0004_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.FloatField()),
                ('Plazo', models.IntegerField()),
                ('Tipo_de_Prestamo', models.CharField(max_length=100)),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_list', to='Operaciones_Bancarias.solicitud')),
            ],
        ),
    ]
