# Generated by Django 4.0.6 on 2022-08-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0004_solicitud_divisa_solicitud_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='Solicitud',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='ClienteList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_a_list', to='Operaciones_Bancarias.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Tipo_de_Prestamo',
            field=models.CharField(choices=[('Crédito productivo', 'Crédito productivo'), ('Crédito Comercial Ordinario', 'Crédito Comercial Ordinario'), ('Crédito Comercial Prioritario', 'Crédito Comercial Prioritario'), ('Crédito de Consumo Ordinario', 'Crédito de Consumo Ordinario'), ('Crédito Educativo', 'Crédito Educativo')], default='Crédito Educativo', max_length=40),
        ),
    ]
