# Generated by Django 4.0.6 on 2022-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0005_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Monto',
            field=models.FloatField(help_text='meses'),
        ),
    ]
