# Generated by Django 4.0.6 on 2022-08-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0005_remove_prestamo_solicitud_prestamo_clientelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='Divisa',
            field=models.CharField(choices=[('Dolar', 'Dolar'), ('Euro', 'Euro'), ('Yen Japones', 'Yen Japones'), ('Libra Esterlina', 'Libra Esterlina'), ('Franco Suizo', 'Franco Suizo')], default='Dolar', max_length=20),
        ),
    ]
