# Generated by Django 4.0.6 on 2022-08-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0006_alter_prestamo_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Plazo',
            field=models.IntegerField(help_text='meses'),
        ),
    ]
