# Generated by Django 4.0.6 on 2022-08-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones_Bancarias', '0007_alter_prestamo_monto_alter_prestamo_plazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Operaciones_Bancarias.cliente')),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slct_list', to='Operaciones_Bancarias.solicitud')),
            ],
        ),
    ]
